# 根据Stash官方配置规则进行编写
# 更新日期：2026-08-24

# 规则模式：rule（规则） global（全局代理） direct（全局直连）
mode: rule

# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info

# DNS
dns:
  # 以下填写的 DNS 服务器将会被用来解析 DNS 服务的域名
  # 仅填写 DNS 服务器的 IP 地址
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - system # 使用 iOS 系统 DNS
  # 支持 UDP / TCP / DoT / DoH 协议的 DNS 服务，可以指明具体的连接端口号。
  # 所有 DNS 请求将会直接发送到服务器，不经过任何代理。
  # Stash 会使用最先获得的解析记录回复 DNS 请求
  
  nameserver:
    # 不建议配置超过 2 个 DNS 服务器，会增加系统功耗，如需要DoH自行设置
    - 223.5.5.5
    - 119.29.29.29
  # - https://doh.pub/dns-query
  # - https://dns.alidns.com/dns-query
  # - system # 使用系统 DNS

  # 对部分域名使用单独的 DNS 服务器
  nameserver-policy:
    'www.baidu.com': 114.114.114.114
    '+.proton.me': 1.1.1.1

  # 在以下列表的域名将不会被解析为 fake ip，这些域名相关的解析请求将会返回它们真实的 IP 地址
  fake-ip-filter:
    - '+.lan'
    - '+.local'
    - '+.market.xiaomi.com'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'  
    
    # Google Voices
    - 'lens.l.google.com'
 
    # Nintendo Switch
    - '*.n.n.srv.nintendo.net'
 
    # PlayStation
    - '+.stun.playstation.net'
 
    # XBox
    - 'xbox.*.*.microsoft.com'
    - '*.*.xboxlive.com'
 
    # Microsoft
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'

# 远程代理集
proxy-providers:
  Airport1:
    url: "https://"   #替换为机场订阅地址
    interval: 43200
    path: ./providers/Airport1.yaml
    filter: '^(?!(?:.*流量.*|.*时间.*|.*到期.*)).*$'   # 排除包含“流量”、“时间”、“到期”的节点

# 策略组
proxy-groups:
  - {name: 默认代理, type: select, proxies: [自动选择, 香港节点, 日本节点, 新加坡节点, 美国节点, 手动选择, DIRECT], icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png'}
  - {name: Google, type: select, proxies: [默认代理, 香港节点, 日本节点, 新加坡节点, 美国节点, 手动选择, DIRECT], icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google_Search.png'}
  - {name: ChatGPT, type: select, proxies: [默认代理, 香港节点, 日本节点, 新加坡节点, 美国节点, 手动选择, DIRECT], icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/ChatGPT.png'}
  - {name: Apple, type: select, proxies: [DIRECT, 默认代理, 香港节点, 日本节点, 新加坡节点, 美国节点, 手动选择], icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple_2.png'}
  - {name: GitHub, type: select, proxies: [默认代理, 香港节点, 日本节点, 新加坡节点, 美国节点, 手动选择, DIRECT], icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/GitHub.png'}
  - {name: Social, type: select, proxies: [默认代理, 香港节点, 日本节点, 新加坡节点, 美国节点, 手动选择, DIRECT], icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Facebook.png'}
  - {name: Microsoft, type: select, proxies: [DIRECT, 默认代理, 香港节点, 日本节点, 新加坡节点, 美国节点, 手动选择], icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Windows.png'}
  - {name: Games, type: select, proxies: [默认代理, 香港节点, 日本节点, 新加坡节点, 美国节点, 手动选择, DIRECT], icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Game.png'}
  - {name: NETFLIX, type: select, proxies: [默认代理, 香港节点, 日本节点, 新加坡节点, 美国节点, 手动选择, DIRECT], icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Netflix.png'}
  - {name: Spotify, type: select, proxies: [默认代理, 香港节点, 日本节点, 新加坡节点, 美国节点, 手动选择, DIRECT], icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Spotify.png'}
  - {name: PayPal, type: select, proxies: [默认代理, 香港节点, 日本节点, 新加坡节点, 美国节点, 手动选择, DIRECT], icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Paypal.png'}
  - {name: Shield, type: select, proxies: [默认代理, 香港节点, 日本节点, 新加坡节点, 美国节点, 手动选择, DIRECT, REJECT], icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Lock.png'}
  - {name: 漏网之鱼, type: select, proxies: [默认代理, 香港节点, 日本节点, 新加坡节点, 美国节点, 手动选择, DIRECT], icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png'}
  - {name: 香港节点, type: url-test, use: [Airport1], filter: '(?i)(?:香港|港|HK|HKG|Hong\\s*Kong|HongKong)', tolerance: 20, interval: 600, lazy: true, icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/HK.png'}
  - {name: 日本节点, type: url-test, use: [Airport1], filter: '(?i)(?:日本|日|JP|JPN|Japan)', tolerance: 20, interval: 600, lazy: true, icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/JP.png'}
  - {name: 新加坡节点, type: url-test, use: [Airport1], filter: '(?i)(?:新加坡|新|SG|SGP|Singapore)', tolerance: 20, interval: 600, lazy: true, icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/SG.png'}
  - {name: 美国节点, type: url-test, use: [Airport1], filter: '(?i)(?:美国|美|US|USA|United\\s*States|UnitedStates)', tolerance: 20, interval: 600, lazy: true, icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/US.png'}
  - {name: 自动选择, type: url-test, use: [Airport1], filter: '(?i)(?:香港|港|HK|HKG|Hong\\s*Kong|HongKong|日本|日|JP|JPN|Japan|新加坡|新|SG|SGP|Singapore|美国|美|US|USA|United\\s*States|UnitedStates)', tolerance: 30, interval: 600, lazy: true, icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Round_Robin.png'}
  - {name: 手动选择, type: select, use: [Airport1], icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png'}

# Rule Providers
rule-providers:
  private_domain: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs", path: ./rules/private_domain.mrs, interval: 86400}
  ai: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs", path: ./rules/ai.mrs, interval: 86400}
  youtube_domain: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs", path: ./rules/youtube.mrs, interval: 86400}
  google_domain: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs", path: ./rules/google.mrs, interval: 86400}
  github_domain: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs", path: ./rules/github.mrs, interval: 86400}
  spotify_domain: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs", path: ./rules/spotify.mrs, interval: 86400}
  telegram_domain: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs", path: ./rules/telegram.mrs, interval: 86400}
  netflix_domain: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs", path: ./rules/netflix.mrs, interval: 86400}
  paypal_domain: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs", path: ./rules/paypal.mrs, interval: 86400}
  whatsapp_domain: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/whatsapp.mrs", path: ./rules/whatsapp.mrs, interval: 86400}
  facebook_domain: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/facebook.mrs", path: ./rules/facebook.mrs, interval: 86400}
  instagram_domain: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/instagram.mrs", path: ./rules/instagram.mrs, interval: 86400}
  snapchat_domain: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/snap.mrs", path: ./rules/snapchat.mrs, interval: 86400}
  twitter_domain: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.mrs", path: ./rules/twitter.mrs, interval: 86400}
  discord_domain: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/discord.mrs", path: ./rules/discord.mrs, interval: 86400}
  microsoft_domain: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs", path: ./rules/microsoft.mrs, interval: 86400}
  apple_domain: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs", path: ./rules/apple.mrs, interval: 86400}
  porn_domain: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-porn.mrs", path: ./rules/porn.mrs, interval: 86400}
  games_domain: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games-!cn.mrs", path: ./rules/games.mrs, interval: 86400}
  geolocation-!cn: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs", path: ./rules/geolocation-!cn.mrs, interval: 86400}
  cn_domain: {behavior: domain, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs", path: ./rules/cn.mrs, interval: 86400}
  private_ip: {behavior: ipcidr, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs", path: ./rules/private_ip.mrs, interval: 86400}
  cn_ip: {behavior: ipcidr, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs", path: ./rules/cn_ip.mrs, interval: 86400}
  google_ip: {behavior: ipcidr, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs", path: ./rules/google_ip.mrs, interval: 86400}
  telegram_ip: {behavior: ipcidr, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs", path: ./rules/telegram_ip.mrs, interval: 86400}
  netflix_ip: {behavior: ipcidr, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs", path: ./rules/netflix_ip.mrs, interval: 86400}
  apple_ip: {behavior: ipcidr, format: mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs", path: ./rules/apple_ip.mrs, interval: 86400}

# 分流规则
rules:
  - DOMAIN-SUFFIX,unpkg.com,DIRECT
  - DOMAIN-SUFFIX,jsdelivr.net,DIRECT
  - DOMAIN-SUFFIX,xhscdn.com,DIRECT
  - DOMAIN-SUFFIX,clashmi.app,默认代理
  - DOMAIN-SUFFIX,overcast.fm,默认代理
  - DOMAIN-SUFFIX,overcast-cdn.com,默认代理
  - DOMAIN-SUFFIX,jpush.cn,默认代理
  - RULE-SET,cn_domain,DIRECT
  - RULE-SET,private_domain,DIRECT
  - RULE-SET,private_ip,DIRECT,no-resolve
  - RULE-SET,ai,ChatGPT
  - RULE-SET,github_domain,GitHub
# - RULE-SET,youtube_domain,Google
  - RULE-SET,google_domain,Google
  - RULE-SET,whatsapp_domain,Social
  - RULE-SET,instagram_domain,Social
  - RULE-SET,facebook_domain,Social
  - RULE-SET,snapchat_domain,Social
  - RULE-SET,telegram_domain,Social
  - RULE-SET,twitter_domain,Social
  - RULE-SET,discord_domain,Social
  - RULE-SET,microsoft_domain,Microsoft
  - RULE-SET,apple_domain,Apple
  - RULE-SET,spotify_domain,Spotify
  - RULE-SET,porn_domain,Shield
  - DOMAIN-SUFFIX,91porn.com,Shield
  - RULE-SET,netflix_domain,NETFLIX
  - RULE-SET,games_domain,Games
  - DOMAIN-SUFFIX,2ksports.com,Games
  - DOMAIN-SUFFIX,marketingcloudapis.com,Games
  - RULE-SET,paypal_domain,PayPal
  - RULE-SET,telegram_ip,Social,no-resolve
  - RULE-SET,apple_ip,Apple,no-resolve
  - RULE-SET,google_ip,Google,no-resolve
  - RULE-SET,netflix_ip,NETFLIX,no-resolve
  - RULE-SET,geolocation-!cn,默认代理
  - RULE-SET,cn_ip,DIRECT,no-resolve
  - MATCH,漏网之鱼
